# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperarSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario-Recuperar')),
                ('data_criacao', models.DateTimeField()),
                ('token',  models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'RecuperarSenha',
                'verbose_name_plural': 'RecuperarSenha',
            }
        )
    ]
