# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170613_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperarsenha',
            name='token',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
