---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - sudo apt-get update
  - >
    sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
  - >
    curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" |
    sudo apt-key add -
  - >
    sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d

script:
  - ./test.sh

after_script:
  - docker-compose down
...
