agendadb:
  image: postgres:9.6.5
  environment:
    POSTGRES_PASSWORD: agenda
    POSTGRES_USER: agenda
    POSTGRES_DB: agenda
    PGDATA : /var/lib/postgresql/data/
  volumes:
    - ./agendadb_data:/var/lib/postgresql/data/
  ports:
    - "5532:5432"
agenda:
  image: interlegis/agenda-evento-back_end
  volumes:
    - ./agenda_data:/var/interlegis/agenda/data
    - ./agenda_media/pdf:/var/interlegis/agenda/media/pdf
  environment:
    ADMIN_PASSWORD: 'interlegis'
    SECRETARY_PASSWORD: 'interlegis'
    DEBUG: 'False'
    USE_TLS: 'True'
    EMAIL_PORT: '587'
    EMAIL_HOST: 'smtp.interlegis.leg.br'
    EMAIL_HOST_USER: 'sapl-test@interlegis.leg.br'
    EMAIL_HOST_PASSWORD: 'cV6mkAFQjT'
    EMAIL_SEND_USER: 'sapl-test@interlegis.leg.br'
    DEFAULT_FROM_EMAIL: 'sapl-test@interlegis.leg.br'
    SERVER_EMAIL: 'sapl-test@interlegis.leg.br'
    SESSION_COOKIE_SECURE: 'True'
    CSRF_COOKIE_SECURE: 'True'
    SECURE_BROWSER_XSS_FILTER: 'True'
    SECURE_CONTENT_TYPE_NOSNIFF: 'True'
    X_FRAME_OPTIONS: 'True'
  links:
    - agendadb
  ports:
    - "8000:8000"
