agendadb:
  image: postgres:9.6.5
  environment:
    POSTGRES_PASSWORD: agenda
    POSTGRES_USER: agenda
    POSTGRES_DB: agenda
    PGDATA : /var/lib/postgresql/data/
  volumes:
    - ./agendadb_data:/var/lib/postgresql/data/
  ports:
    - "5532:5432"
agenda:
  build: .
  volumes:
    - ./agenda_data:/var/interlegis/agenda/data
    - ./agenda_media/pdf:/var/interlegis/agenda/media/pdf
  environment:
    ADMIN_PASSWORD: 'interlegis'
    SECRETARY_PASSWORD: 'interlegis'
    ADMIN_EMAIL: 'email@dominio.net'
    DEBUG: 'False'
    USE_TLS: 'False' 
    EMAIL_PORT: 587
    EMAIL_HOST: smtp.dominio.net
    EMAIL_HOST_USER: usuariosmtp
    EMAIL_HOST_PASSWORD: senhasmtp
    SESSION_COOKIE_SECURE: 'True'
    CSRF_COOKIE_SECURE: 'True'
    SECURE_BROWSER_XSS_FILTER: 'True'
    SECURE_CONTENT_TYPE_NOSNIFF: 'True'
    X_FRAME_OPTIONS: 'True'
  links:
    - agendadb
  ports:
    - "8000:8000"
agenda_frontend:
  image: swallville/agenda-evento
  ports:
    - "80:80"
