# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='is_cancelado',
            new_name='cancelado',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='is_legislativo',
            new_name='legislativo',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='is_cancelado',
            new_name='recebido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='is_recebido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='is_reservado',
        ),
        migrations.AddField(
            model_name='evento',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ano',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('P', 'Pre-reserva'), ('R', 'Reservado'), ('C', 'Cancelado')], default=b'P', max_length=100),
        ),
    ]
