# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0004_evento_video_conferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(9, 39, 0, 94301)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
