# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0007_reserva_validade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='validade',
            new_name='validade_pre_reserva',
        ),
    ]
