# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 3, 14, 44, 0, 664383, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('data_fim', models.DateField()),
                ('hora_fim', models.TimeField()),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField(blank=True)),
                ('local', models.CharField(choices=[('SR', 'Sala de Reunioes'), ('AI', 'Auditorio Interlegis')], max_length=100)),
                ('video_conferencia', models.BooleanField(default=False)),
                ('publicado_agenda', models.BooleanField(default=False)),
                ('legislativo', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('causa_cancelamento', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventoTramitacaoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=100)),
                ('data_modificacao', models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 3, 14, 44, 0, 682714, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Log Evento Tramitado',
                'verbose_name_plural': 'Log Eventos Tramitados',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2017, 7, 3, 14, 44, 0, 680908, tzinfo=utc))),
                ('status', models.CharField(choices=[('P', 'Pre-reserva'), ('R', 'Reservado'), ('C', 'Cancelado'), ('I', 'Impedido')], default=b'P', max_length=100)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('nr_referencia', models.CharField(blank=True, max_length=50, unique=True)),
                ('ano', models.CharField(blank=True, max_length=4)),
                ('validade_pre_reserva', models.DateField(blank=True)),
                ('recebido', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_agenda.Evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsavel-Reserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('lotacao', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
            },
        ),
        migrations.AddField(
            model_name='eventotramitacaolog',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_agenda.Reserva', verbose_name='Reserva'),
        ),
        migrations.AddField(
            model_name='eventotramitacaolog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_agenda.Responsavel', verbose_name='Responsavel-Evento'),
        ),
    ]
