# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0002_auto_20170213_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='responsavel_fk',
            new_name='responsavel',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='evento_fk',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='usario_fk',
            new_name='usario',
        ),
    ]
