# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0006_evento_publicado_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='validade',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
