# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0007_auto_20170817_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventotramitacaolog',
            name='arquivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_agenda.Arquivo', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='cronlog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 17, 18, 0, 46, 500211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventotramitacaolog',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 17, 18, 0, 46, 517999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 18, 0, 46, 514789, tzinfo=utc)),
        ),
    ]
