# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0008_auto_20170216_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('P', 'Pre-reserva'), ('R', 'Reservado'), ('C', 'Cancelado'), ('I', 'Impedido')], default=b'P', max_length=100),
        ),
    ]
