# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0009_auto_20170221_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 12, 51, 46, 373204, tzinfo=utc)),
        ),
    ]
