# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0011_auto_20170822_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'Arquivo Tramitado', 'verbose_name_plural': 'Arquivos Tramitados'},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 22, 20, 0, 25, 934757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cronlog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 22, 20, 0, 25, 865549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventotramitacaolog',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 22, 20, 0, 25, 937725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 22, 20, 0, 25, 924407, tzinfo=utc)),
        ),
    ]
