# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0012_auto_20170822_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronlog',
            options={'verbose_name': 'Cron Log', 'verbose_name_plural': 'Cron Logs'},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 24, 17, 16, 43, 145673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cronlog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 24, 17, 16, 43, 106749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventotramitacaolog',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 24, 17, 16, 43, 146429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 17, 16, 43, 142048, tzinfo=utc)),
        ),
    ]
