# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0013_auto_20170224_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 21, 36, 16, 511977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('P', 'Pre-reserva'), ('R', 'Reservado'), ('C', 'Cancelado'), ('I', 'Impedido')], default='P', max_length=100),
        ),
    ]
