# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0013_auto_20170224_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 21, 47, 48, 412855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
