# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0014_auto_20170404_1847'),
        ('rest_agenda', '0014_auto_20170401_2136'),
    ]

    operations = [
    ]
