# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0015_merge_20170406_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 24, 42, 289578, tzinfo=utc)),
        ),
    ]
