# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 16:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_agenda', '0025_auto_20170519_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTramitacaoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_modificacao', models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 6, 16, 41, 11, 797743, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Log Eventos Tramitados',
                'verbose_name_plural': 'Log Eventos Tramitados',
            },
        ),
        migrations.AlterField(
            model_name='cronlog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 6, 16, 41, 11, 782914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 6, 16, 41, 11, 796478, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='eventotramitacaolog',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_agenda.Reserva', verbose_name='Reserva'),
        ),
        migrations.AddField(
            model_name='eventotramitacaolog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
