# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_agenda', '0042_auto_20170614_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventotramitacaolog',
            options={'verbose_name': 'Log Evento Tramitado', 'verbose_name_plural': 'Log Eventos Tramitados'},
        ),
        migrations.AlterField(
            model_name='cronlog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 26, 11, 22, 45, 733046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventotramitacaolog',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 26, 11, 22, 45, 754973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 11, 22, 45, 753115, tzinfo=utc)),
        ),
    ]
